/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tara zadlyka
 */
public class diagnosa extends javax.swing.JFrame {

    /**
     * Creates new form pertanyaan1
     */
    String penyakit = "";
    public diagnosa() {
        initComponents();
    }
    public diagnosa(String[] p, boolean[] bp) {
        initComponents();
        //R1
        if(bp[0]&&bp[1]&&bp[2]&&bp[3]&&bp[4]&&bp[5]&&bp[6]&&bp[21]&&bp[22]){
            penyakit = "Jantung Koroner";
        }else if(bp[3]&&bp[6]&&bp[7]&&bp[9]&&bp[10]){
            penyakit = "Otot Jantung (Kardiomiopati)";
        }else if(bp[11]&&bp[12]&&bp[13]&&bp[21]&&bp[8]){
            penyakit = "Penyakit Jantung Iskemik";
        }else if(bp[3]&&bp[14]&&bp[15]){
            penyakit = "Gagal Jantung";
        }else if(bp[23]&&bp[16]&&bp[7]&&bp[17]&&bp[10]){
            penyakit = "Hipertensi";
        }else if(bp[10]&&bp[9]&&bp[0]&&bp[3]&&bp[18]&&bp[8]){
            penyakit = "Penyakit Katup Jantung";
        }else if(bp[19]&&bp[8]&&bp[1]&&bp[0]){
            penyakit = "Penyakit Jantung Hipertrofik (Kardiomegali)";
        }       
        
        menderita.setText(penyakit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTA = new javax.swing.JLabel();
        LTA1 = new javax.swing.JLabel();
        menderita = new javax.swing.JLabel();
        LTA3 = new javax.swing.JLabel();
        buttontext2 = new javax.swing.JPanel();
        textb2 = new javax.swing.JLabel();
        LTA4 = new javax.swing.JLabel();
        LTA5 = new javax.swing.JLabel();
        LTA6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        LTA.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        LTA.setForeground(new java.awt.Color(171, 182, 200));
        LTA.setText("Document A");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LTA1.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        LTA1.setForeground(new java.awt.Color(171, 182, 200));
        LTA1.setText("Kemungkinan Anda Terkena Penyakit :");
        getContentPane().add(LTA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 420, -1));

        menderita.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        menderita.setForeground(new java.awt.Color(171, 182, 200));
        menderita.setText(".......");
        getContentPane().add(menderita, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, -1));

        LTA3.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        LTA3.setForeground(new java.awt.Color(171, 182, 200));
        LTA3.setText("Diagnosa dan Solusi");
        getContentPane().add(LTA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 180, -1));

        buttontext2.setBackground(new java.awt.Color(171, 182, 200));

        textb2.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        textb2.setForeground(new java.awt.Color(255, 255, 255));
        textb2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textb2.setText("Home");
        textb2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textb2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textb2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                textb2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout buttontext2Layout = new javax.swing.GroupLayout(buttontext2);
        buttontext2.setLayout(buttontext2Layout);
        buttontext2Layout.setHorizontalGroup(
            buttontext2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textb2, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        buttontext2Layout.setVerticalGroup(
            buttontext2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textb2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(buttontext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 120, 30));

        LTA4.setFont(new java.awt.Font("Futura Bk BT", 0, 14)); // NOI18N
        LTA4.setForeground(new java.awt.Color(171, 182, 200));
        LTA4.setText("Silakan Periksa kondisi anda ke dokter Spesialis Jantung");
        getContentPane().add(LTA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 400, -1));

        LTA5.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        LTA5.setForeground(new java.awt.Color(171, 182, 200));
        LTA5.setText("Diagnosa : Berdasarkan gejala yang anda rasakan");
        getContentPane().add(LTA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 420, -1));

        LTA6.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        LTA6.setForeground(new java.awt.Color(171, 182, 200));
        LTA6.setText("Solusi : ");
        getContentPane().add(LTA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/SIM.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textb2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textb2MouseClicked
        // TODO add your handling code here:
        halaman_utama home = new halaman_utama();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_textb2MouseClicked

    private void textb2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textb2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_textb2MouseEntered

    private void textb2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textb2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_textb2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pertanyaan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pertanyaan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pertanyaan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pertanyaan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pertanyaan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LTA;
    private javax.swing.JLabel LTA1;
    private javax.swing.JLabel LTA3;
    private javax.swing.JLabel LTA4;
    private javax.swing.JLabel LTA5;
    private javax.swing.JLabel LTA6;
    private javax.swing.JPanel buttontext2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel menderita;
    private javax.swing.JLabel textb2;
    // End of variables declaration//GEN-END:variables
}
